/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as AuthDashboardRouteImport } from './routes/_auth/dashboard'
import { Route as AuthPosRouteImport } from './routes/_auth/pos'
import { Route as AuthBillingIndexRouteImport } from './routes/_auth/billing/index'
import { Route as AuthBillingIdRouteImport } from './routes/_auth/billing/$id'
import { Route as AuthCustomersIndexRouteImport } from './routes/_auth/customers/index'
import { Route as AuthCustomersIdRouteImport } from './routes/_auth/customers/$id'
import { Route as AuthInventoryIndexRouteImport } from './routes/_auth/inventory/index'
import { Route as AuthInventoryIdRouteImport } from './routes/_auth/inventory/$id'
import { Route as AuthInventoryNewRouteImport } from './routes/_auth/inventory/new'
import { Route as AuthPurchasesIndexRouteImport } from './routes/_auth/purchases/index'
import { Route as AuthPurchasesNewRouteImport } from './routes/_auth/purchases/new'
import { Route as AuthReportsIndexRouteImport } from './routes/_auth/reports/index'
import { Route as AuthSettingsStoreRouteImport } from './routes/_auth/settings/store'
import { Route as AuthSettingsUsersRouteImport } from './routes/_auth/settings/users'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthDashboardRoute = AuthDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthRoute,
} as any)
const AuthPosRoute = AuthPosRouteImport.update({
  id: '/pos',
  path: '/pos',
  getParentRoute: () => AuthRoute,
} as any)
const AuthBillingIndexRoute = AuthBillingIndexRouteImport.update({
  id: '/billing/',
  path: '/billing/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthBillingIdRoute = AuthBillingIdRouteImport.update({
  id: '/billing/$id',
  path: '/billing/$id',
  getParentRoute: () => AuthRoute,
} as any)
const AuthCustomersIndexRoute = AuthCustomersIndexRouteImport.update({
  id: '/customers/',
  path: '/customers/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthCustomersIdRoute = AuthCustomersIdRouteImport.update({
  id: '/customers/$id',
  path: '/customers/$id',
  getParentRoute: () => AuthRoute,
} as any)
const AuthInventoryIndexRoute = AuthInventoryIndexRouteImport.update({
  id: '/inventory/',
  path: '/inventory/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthInventoryIdRoute = AuthInventoryIdRouteImport.update({
  id: '/inventory/$id',
  path: '/inventory/$id',
  getParentRoute: () => AuthRoute,
} as any)
const AuthInventoryNewRoute = AuthInventoryNewRouteImport.update({
  id: '/inventory/new',
  path: '/inventory/new',
  getParentRoute: () => AuthRoute,
} as any)
const AuthPurchasesIndexRoute = AuthPurchasesIndexRouteImport.update({
  id: '/purchases/',
  path: '/purchases/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthPurchasesNewRoute = AuthPurchasesNewRouteImport.update({
  id: '/purchases/new',
  path: '/purchases/new',
  getParentRoute: () => AuthRoute,
} as any)
const AuthReportsIndexRoute = AuthReportsIndexRouteImport.update({
  id: '/reports/',
  path: '/reports/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSettingsStoreRoute = AuthSettingsStoreRouteImport.update({
  id: '/settings/store',
  path: '/settings/store',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSettingsUsersRoute = AuthSettingsUsersRouteImport.update({
  id: '/settings/users',
  path: '/settings/users',
  getParentRoute: () => AuthRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/dashboard': typeof AuthDashboardRoute
  '/pos': typeof AuthPosRoute
  '/billing/$id': typeof AuthBillingIdRoute
  '/customers/$id': typeof AuthCustomersIdRoute
  '/inventory/$id': typeof AuthInventoryIdRoute
  '/inventory/new': typeof AuthInventoryNewRoute
  '/purchases/new': typeof AuthPurchasesNewRoute
  '/settings/store': typeof AuthSettingsStoreRoute
  '/settings/users': typeof AuthSettingsUsersRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/billing/': typeof AuthBillingIndexRoute
  '/customers/': typeof AuthCustomersIndexRoute
  '/inventory/': typeof AuthInventoryIndexRoute
  '/purchases/': typeof AuthPurchasesIndexRoute
  '/reports/': typeof AuthReportsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/dashboard': typeof AuthDashboardRoute
  '/pos': typeof AuthPosRoute
  '/billing/$id': typeof AuthBillingIdRoute
  '/customers/$id': typeof AuthCustomersIdRoute
  '/inventory/$id': typeof AuthInventoryIdRoute
  '/inventory/new': typeof AuthInventoryNewRoute
  '/purchases/new': typeof AuthPurchasesNewRoute
  '/settings/store': typeof AuthSettingsStoreRoute
  '/settings/users': typeof AuthSettingsUsersRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/billing': typeof AuthBillingIndexRoute
  '/customers': typeof AuthCustomersIndexRoute
  '/inventory': typeof AuthInventoryIndexRoute
  '/purchases': typeof AuthPurchasesIndexRoute
  '/reports': typeof AuthReportsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_auth/dashboard': typeof AuthDashboardRoute
  '/_auth/pos': typeof AuthPosRoute
  '/_auth/billing/$id': typeof AuthBillingIdRoute
  '/_auth/customers/$id': typeof AuthCustomersIdRoute
  '/_auth/inventory/$id': typeof AuthInventoryIdRoute
  '/_auth/inventory/new': typeof AuthInventoryNewRoute
  '/_auth/purchases/new': typeof AuthPurchasesNewRoute
  '/_auth/settings/store': typeof AuthSettingsStoreRoute
  '/_auth/settings/users': typeof AuthSettingsUsersRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_auth/billing/': typeof AuthBillingIndexRoute
  '/_auth/customers/': typeof AuthCustomersIndexRoute
  '/_auth/inventory/': typeof AuthInventoryIndexRoute
  '/_auth/purchases/': typeof AuthPurchasesIndexRoute
  '/_auth/reports/': typeof AuthReportsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/dashboard'
    | '/pos'
    | '/billing/$id'
    | '/customers/$id'
    | '/inventory/$id'
    | '/inventory/new'
    | '/purchases/new'
    | '/settings/store'
    | '/settings/users'
    | '/api/auth/$'
    | '/billing/'
    | '/customers/'
    | '/inventory/'
    | '/purchases/'
    | '/reports/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/dashboard'
    | '/pos'
    | '/billing/$id'
    | '/customers/$id'
    | '/inventory/$id'
    | '/inventory/new'
    | '/purchases/new'
    | '/settings/store'
    | '/settings/users'
    | '/api/auth/$'
    | '/billing'
    | '/customers'
    | '/inventory'
    | '/purchases'
    | '/reports'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/login'
    | '/register'
    | '/_auth/dashboard'
    | '/_auth/pos'
    | '/_auth/billing/$id'
    | '/_auth/customers/$id'
    | '/_auth/inventory/$id'
    | '/_auth/inventory/new'
    | '/_auth/purchases/new'
    | '/_auth/settings/store'
    | '/_auth/settings/users'
    | '/api/auth/$'
    | '/_auth/billing/'
    | '/_auth/customers/'
    | '/_auth/inventory/'
    | '/_auth/purchases/'
    | '/_auth/reports/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/dashboard': {
      id: '/_auth/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthDashboardRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/pos': {
      id: '/_auth/pos'
      path: '/pos'
      fullPath: '/pos'
      preLoaderRoute: typeof AuthPosRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/billing/': {
      id: '/_auth/billing/'
      path: '/billing'
      fullPath: '/billing/'
      preLoaderRoute: typeof AuthBillingIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/billing/$id': {
      id: '/_auth/billing/$id'
      path: '/billing/$id'
      fullPath: '/billing/$id'
      preLoaderRoute: typeof AuthBillingIdRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/customers/': {
      id: '/_auth/customers/'
      path: '/customers'
      fullPath: '/customers/'
      preLoaderRoute: typeof AuthCustomersIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/customers/$id': {
      id: '/_auth/customers/$id'
      path: '/customers/$id'
      fullPath: '/customers/$id'
      preLoaderRoute: typeof AuthCustomersIdRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/inventory/': {
      id: '/_auth/inventory/'
      path: '/inventory'
      fullPath: '/inventory/'
      preLoaderRoute: typeof AuthInventoryIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/inventory/$id': {
      id: '/_auth/inventory/$id'
      path: '/inventory/$id'
      fullPath: '/inventory/$id'
      preLoaderRoute: typeof AuthInventoryIdRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/inventory/new': {
      id: '/_auth/inventory/new'
      path: '/inventory/new'
      fullPath: '/inventory/new'
      preLoaderRoute: typeof AuthInventoryNewRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/purchases/': {
      id: '/_auth/purchases/'
      path: '/purchases'
      fullPath: '/purchases/'
      preLoaderRoute: typeof AuthPurchasesIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/purchases/new': {
      id: '/_auth/purchases/new'
      path: '/purchases/new'
      fullPath: '/purchases/new'
      preLoaderRoute: typeof AuthPurchasesNewRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/reports/': {
      id: '/_auth/reports/'
      path: '/reports'
      fullPath: '/reports/'
      preLoaderRoute: typeof AuthReportsIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/settings/store': {
      id: '/_auth/settings/store'
      path: '/settings/store'
      fullPath: '/settings/store'
      preLoaderRoute: typeof AuthSettingsStoreRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/settings/users': {
      id: '/_auth/settings/users'
      path: '/settings/users'
      fullPath: '/settings/users'
      preLoaderRoute: typeof AuthSettingsUsersRouteImport
      parentRoute: typeof AuthRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthRouteChildren {
  AuthDashboardRoute: typeof AuthDashboardRoute
  AuthPosRoute: typeof AuthPosRoute
  AuthBillingIdRoute: typeof AuthBillingIdRoute
  AuthCustomersIdRoute: typeof AuthCustomersIdRoute
  AuthInventoryIdRoute: typeof AuthInventoryIdRoute
  AuthInventoryNewRoute: typeof AuthInventoryNewRoute
  AuthPurchasesNewRoute: typeof AuthPurchasesNewRoute
  AuthSettingsStoreRoute: typeof AuthSettingsStoreRoute
  AuthSettingsUsersRoute: typeof AuthSettingsUsersRoute
  AuthBillingIndexRoute: typeof AuthBillingIndexRoute
  AuthCustomersIndexRoute: typeof AuthCustomersIndexRoute
  AuthInventoryIndexRoute: typeof AuthInventoryIndexRoute
  AuthPurchasesIndexRoute: typeof AuthPurchasesIndexRoute
  AuthReportsIndexRoute: typeof AuthReportsIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthDashboardRoute: AuthDashboardRoute,
  AuthPosRoute: AuthPosRoute,
  AuthBillingIdRoute: AuthBillingIdRoute,
  AuthCustomersIdRoute: AuthCustomersIdRoute,
  AuthInventoryIdRoute: AuthInventoryIdRoute,
  AuthInventoryNewRoute: AuthInventoryNewRoute,
  AuthPurchasesNewRoute: AuthPurchasesNewRoute,
  AuthSettingsStoreRoute: AuthSettingsStoreRoute,
  AuthSettingsUsersRoute: AuthSettingsUsersRoute,
  AuthBillingIndexRoute: AuthBillingIndexRoute,
  AuthCustomersIndexRoute: AuthCustomersIndexRoute,
  AuthInventoryIndexRoute: AuthInventoryIndexRoute,
  AuthPurchasesIndexRoute: AuthPurchasesIndexRoute,
  AuthReportsIndexRoute: AuthReportsIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
